/* tslint:disable */
/* eslint-disable */
/**
 * Bus Ticket Booking API
 * API for managing bus ticket booking application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response object for bus details
 * @export
 * @interface BusResponse
 */
export interface BusResponse {
    /**
     * Unique identifier for the bus
     * @type {string}
     * @memberof BusResponse
     */
    busNumber: string;
    /**
     * Capacity of the bus
     * @type {number}
     * @memberof BusResponse
     */
    capacity: number;
}

/**
 * Check if a given object implements the BusResponse interface.
 */
export function instanceOfBusResponse(value: object): value is BusResponse {
    if (!('busNumber' in value) || value['busNumber'] === undefined) return false;
    if (!('capacity' in value) || value['capacity'] === undefined) return false;
    return true;
}

export function BusResponseFromJSON(json: any): BusResponse {
    return BusResponseFromJSONTyped(json, false);
}

export function BusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'busNumber': json['busNumber'],
        'capacity': json['capacity'],
    };
}

export function BusResponseToJSON(json: any): BusResponse {
    return BusResponseToJSONTyped(json, false);
}

export function BusResponseToJSONTyped(value?: BusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'busNumber': value['busNumber'],
        'capacity': value['capacity'],
    };
}

