/* tslint:disable */
/* eslint-disable */
/**
 * Bus Ticket Booking API
 * API for managing bus ticket booking application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request object for creating or updating a bus
 * @export
 * @interface BusRequest
 */
export interface BusRequest {
    /**
     * Unique identifier for the bus
     * @type {string}
     * @memberof BusRequest
     */
    busNumber: string;
    /**
     * Capacity of the bus
     * @type {number}
     * @memberof BusRequest
     */
    capacity: number;
}

/**
 * Check if a given object implements the BusRequest interface.
 */
export function instanceOfBusRequest(value: object): value is BusRequest {
    if (!('busNumber' in value) || value['busNumber'] === undefined) return false;
    if (!('capacity' in value) || value['capacity'] === undefined) return false;
    return true;
}

export function BusRequestFromJSON(json: any): BusRequest {
    return BusRequestFromJSONTyped(json, false);
}

export function BusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'busNumber': json['busNumber'],
        'capacity': json['capacity'],
    };
}

export function BusRequestToJSON(json: any): BusRequest {
    return BusRequestToJSONTyped(json, false);
}

export function BusRequestToJSONTyped(value?: BusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'busNumber': value['busNumber'],
        'capacity': value['capacity'],
    };
}

