/* tslint:disable */
/* eslint-disable */
/**
 * Bus Ticket Booking API
 * API for managing bus ticket booking application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request object for creating or updating a city
 * @export
 * @interface CityRequest
 */
export interface CityRequest {
    /**
     * Name of the city
     * @type {string}
     * @memberof CityRequest
     */
    name: string;
    /**
     * Time zone of the city
     * @type {string}
     * @memberof CityRequest
     */
    zoneId?: string;
}

/**
 * Check if a given object implements the CityRequest interface.
 */
export function instanceOfCityRequest(value: object): value is CityRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CityRequestFromJSON(json: any): CityRequest {
    return CityRequestFromJSONTyped(json, false);
}

export function CityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'zoneId': json['zoneId'] == null ? undefined : json['zoneId'],
    };
}

export function CityRequestToJSON(json: any): CityRequest {
    return CityRequestToJSONTyped(json, false);
}

export function CityRequestToJSONTyped(value?: CityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'zoneId': value['zoneId'],
    };
}

