/* tslint:disable */
/* eslint-disable */
/**
 * Bus Ticket Booking API
 * API for managing bus ticket booking application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response object for payment processing
 * @export
 * @interface PaymentResponse
 */
export interface PaymentResponse {
    /**
     * Message indicating the result of the payment processing
     * @type {string}
     * @memberof PaymentResponse
     */
    message: string;
}

/**
 * Check if a given object implements the PaymentResponse interface.
 */
export function instanceOfPaymentResponse(value: object): value is PaymentResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PaymentResponseFromJSON(json: any): PaymentResponse {
    return PaymentResponseFromJSONTyped(json, false);
}

export function PaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function PaymentResponseToJSON(json: any): PaymentResponse {
    return PaymentResponseToJSONTyped(json, false);
}

export function PaymentResponseToJSONTyped(value?: PaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

