/* tslint:disable */
/* eslint-disable */
/**
 * Bus Ticket Booking API
 * API for managing bus ticket booking application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response object for route details
 * @export
 * @interface RouteResponse
 */
export interface RouteResponse {
    /**
     * Origin of the route
     * @type {string}
     * @memberof RouteResponse
     */
    origin: string;
    /**
     * Destination of the route
     * @type {string}
     * @memberof RouteResponse
     */
    destination: string;
    /**
     * Distance of the route in kilometers
     * @type {number}
     * @memberof RouteResponse
     */
    distance: number;
    /**
     * Duration in hours and minutes
     * @type {string}
     * @memberof RouteResponse
     */
    duration: string;
    /**
     * Base price of the route in CZK
     * @type {number}
     * @memberof RouteResponse
     */
    basePriceCzk: number;
}

/**
 * Check if a given object implements the RouteResponse interface.
 */
export function instanceOfRouteResponse(value: object): value is RouteResponse {
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('distance' in value) || value['distance'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('basePriceCzk' in value) || value['basePriceCzk'] === undefined) return false;
    return true;
}

export function RouteResponseFromJSON(json: any): RouteResponse {
    return RouteResponseFromJSONTyped(json, false);
}

export function RouteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'origin': json['origin'],
        'destination': json['destination'],
        'distance': json['distance'],
        'duration': json['duration'],
        'basePriceCzk': json['basePriceCzk'],
    };
}

export function RouteResponseToJSON(json: any): RouteResponse {
    return RouteResponseToJSONTyped(json, false);
}

export function RouteResponseToJSONTyped(value?: RouteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'origin': value['origin'],
        'destination': value['destination'],
        'distance': value['distance'],
        'duration': value['duration'],
        'basePriceCzk': value['basePriceCzk'],
    };
}

