/* tslint:disable */
/* eslint-disable */
/**
 * Bus Ticket Booking API
 * API for managing bus ticket booking application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request object for creating or updating a route
 * @export
 * @interface RouteRequest
 */
export interface RouteRequest {
    /**
     * Origin city of the route
     * @type {string}
     * @memberof RouteRequest
     */
    origin: string;
    /**
     * Destination city of the route
     * @type {string}
     * @memberof RouteRequest
     */
    destination: string;
    /**
     * Distance of the route in kilometers
     * @type {number}
     * @memberof RouteRequest
     */
    distance: number;
    /**
     * Duration in hours and minutes
     * @type {string}
     * @memberof RouteRequest
     */
    duration: string;
    /**
     * Base price of the route in CZK
     * @type {number}
     * @memberof RouteRequest
     */
    basePriceCzk: number;
}

/**
 * Check if a given object implements the RouteRequest interface.
 */
export function instanceOfRouteRequest(value: object): value is RouteRequest {
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('distance' in value) || value['distance'] === undefined) return false;
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('basePriceCzk' in value) || value['basePriceCzk'] === undefined) return false;
    return true;
}

export function RouteRequestFromJSON(json: any): RouteRequest {
    return RouteRequestFromJSONTyped(json, false);
}

export function RouteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'origin': json['origin'],
        'destination': json['destination'],
        'distance': json['distance'],
        'duration': json['duration'],
        'basePriceCzk': json['basePriceCzk'],
    };
}

export function RouteRequestToJSON(json: any): RouteRequest {
    return RouteRequestToJSONTyped(json, false);
}

export function RouteRequestToJSONTyped(value?: RouteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'origin': value['origin'],
        'destination': value['destination'],
        'distance': value['distance'],
        'duration': value['duration'],
        'basePriceCzk': value['basePriceCzk'],
    };
}

