/* tslint:disable */
/* eslint-disable */
/**
 * Bus Ticket Booking API
 * API for managing bus ticket booking application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response object for seat details
 * @export
 * @interface SeatResponse
 */
export interface SeatResponse {
    /**
     * Unique identifier for the seat
     * @type {number}
     * @memberof SeatResponse
     */
    seatNumber: number;
    /**
     * Current status of the seat
     * @type {string}
     * @memberof SeatResponse
     */
    status: SeatResponseStatusEnum;
}


/**
 * @export
 */
export const SeatResponseStatusEnum = {
    Free: 'FREE',
    Blocked: 'BLOCKED',
    Reserved: 'RESERVED'
} as const;
export type SeatResponseStatusEnum = typeof SeatResponseStatusEnum[keyof typeof SeatResponseStatusEnum];


/**
 * Check if a given object implements the SeatResponse interface.
 */
export function instanceOfSeatResponse(value: object): value is SeatResponse {
    if (!('seatNumber' in value) || value['seatNumber'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SeatResponseFromJSON(json: any): SeatResponse {
    return SeatResponseFromJSONTyped(json, false);
}

export function SeatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'seatNumber': json['seatNumber'],
        'status': json['status'],
    };
}

export function SeatResponseToJSON(json: any): SeatResponse {
    return SeatResponseToJSONTyped(json, false);
}

export function SeatResponseToJSONTyped(value?: SeatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seatNumber': value['seatNumber'],
        'status': value['status'],
    };
}

