/* tslint:disable */
/* eslint-disable */
/**
 * Bus Ticket Booking API
 * API for managing bus ticket booking application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SeatResponse,
} from '../models/index';
import {
    SeatResponseFromJSON,
    SeatResponseToJSON,
} from '../models/index';

export interface GetSeatsForScheduledTripRequest {
    scheduledTripId: number;
}

/**
 * 
 */
export class SeatManagementApi extends runtime.BaseAPI {

    /**
     * Retrieve a list of seats available for a specific scheduled trip.
     * Get seats for a scheduled trip
     */
    async getSeatsForScheduledTripRaw(requestParameters: GetSeatsForScheduledTripRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SeatResponse<any>>> {
        if (requestParameters['scheduledTripId'] == null) {
            throw new runtime.RequiredError(
                'scheduledTripId',
                'Required parameter "scheduledTripId" was null or undefined when calling getSeatsForScheduledTrip().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/seats/{scheduled-trip-id}`;
        urlPath = urlPath.replace(`{${"scheduled-trip-id"}}`, encodeURIComponent(String(requestParameters['scheduledTripId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Retrieve a list of seats available for a specific scheduled trip.
     * Get seats for a scheduled trip
     */
    async getSeatsForScheduledTrip(requestParameters: GetSeatsForScheduledTripRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SeatResponse<any>> {
        const response = await this.getSeatsForScheduledTripRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
